Feature/messages router
chingu-voyages/v39-bears-team-11 pull request #111
Opened 2022-05-02 16:36 UTC by uwojeyamudiaga

# Message Router

I have created the message router functionality. However, I do not understand the details of the implementation you have in mind. Please, feel free to add code sample to your review.

closes #107

2022-05-03 17:02 UTC, KhadidjaArezki requested changes

2022-05-03 17:02 UTC, KhadidjaArezki commented on server/Controller/messageController.js
> +    const result = await Message.find({ sender: id, reciever: id })
The find method here will look for a document where the sender field is equal to id AND the receiver is equal to id. As a massage cannot be sent and received by the same user, this query should always return nothing.
This is what I had in mind:
`const result = await Message.find().or([{ sender: id }, { receiver: id }])`
Where the collection is queried for messages where the sender id is equal to id OR the receiver id is equal to id

2022-05-03 17:02 UTC, KhadidjaArezki commented on server/Controller/messageController.js
> +    // if there is a match, send 200 status with result
Before returning the results, here is what I was suggesting we do:
1. Get the current user's list of contacts:
`const friends = await User.findById(id).contacts`
2. Create a chats array:
`chats= []`
3. Loop over each friend_id in the friends array and look for messages where sender === friend_id OR receiver === friend_id:
`for (friend_id in friends) { 
     const friendMessages = result.filter(message=> 
        message.sender === friend_id || message.receiver === friend_id 
 ) 
 chats.concat({ friend_id, messages: friendMessages })`
 4. return chats

2022-05-05 09:44 UTC, uwojeyamudiaga commented on server/Controller/messageController.js
> +    const result = await Message.find({ sender: id, reciever: id })
> The find method here will look for a document where the sender field is equal to id AND the receiver is equal to id. As a massage cannot be sent and received by the same user, this query should always return nothing.

Yeah, it was just a placeholder until I understand what you want me to implement.

2022-05-05 12:42 UTC, uwojeyamudiaga commented on server/Controller/messageController.js
> +    // if there is a match, send 200 status with result
>    `const friends = await User.findById(id).contacts`

Is it not an array of contacts that is stored in `friends`? If it is an array, the `for-in` loop should not work.

2022-05-05 22:35 UTC, KhadidjaArezki commented on server/Controller/messageController.js
> +    // if there is a match, send 200 status with result
Yeah, it was just pseudo-code, I meant loop through the array

2022-05-05 23:26 UTC, KhadidjaArezki approved these changes
Great work as always.

2022-05-05 23:28 UTC, merged