Feature/add friends
chingu-voyages/v39-bears-team-11 pull request #114
Opened 2022-05-07 18:10 UTC by KhadidjaArezki

I fixed some bugs that I didn't notice before and the friends page is now finished. Good thing I didn't have to create new components for this page because I reused the ones from the search task.

2022-05-07 21:40 UTC, jaceksupernak commented
1. When I add friend from searched people it adds and I can see him on my friends list. When I try to add another person the app goes blank. Is it meant to work like this at the moment?
2. Grid template issues below:

Ipad view below:
![Screen Shot 2022-05-07 at 22 34 19](https://user-images.githubusercontent.com/66032213/167272365-3f4cbb00-fe18-420f-8952-f09acb7b514b.png)


This is what shows on my laptop below, is 3 column sided to the left are desired effect?
![Screen Shot 2022-05-07 at 22 34 02](https://user-images.githubusercontent.com/66032213/167272368-834178e5-0816-4ef7-8eda-c4e6e2675f41.png)

2022-05-07 23:38 UTC, KhadidjaArezki commented
1. The addFriend function in userSlice adds a dummy friend object. It doesn't add the result you click on. The page breaks because you are adding the same person twice, and the function is trying to add it again to the friends array in user state. That's what causes the problem.

2. I added a max value to the search result grid items in the grid template because on desktop, if there were one or two friends, they would take up all the available space and that doesn't look good.

2022-05-08 13:40 UTC, KhadidjaArezki commented
I fixed the grid template for the search result items. It should now fit 4 items on laptop. The iPad view is a mystery to me. I could not see that on my browser.

2022-05-08 14:16 UTC, jaceksupernak commented
> I fixed the grid template for the search result items. It should now fit 4 items on laptop. The iPad view is a mystery to me. I could not see that on my browser.

Nice! In chrome the ipad view looks good. In firefox it seems not to be resposive on ipad view. I wonder how it looks on real ipad, perhaps it's all good

2022-05-08 15:49 UTC, KhadidjaArezki commented
I usually use this website to test different viewports : http://whatismyscreenresolution.net/multi-screen-test?

2022-05-09 13:52 UTC, uwojeyamudiaga requested changes
To be honest, this review was difficult for me because the code is not easily readable. The names of variables and components are not close to what they actually do but we do not have time for that now. The code does not have comments that makes it easy to understand what a block of code is doing. Please, can you leave comments in your code to make it easy to read?

2022-05-09 13:52 UTC, moody2times commented on client/src/components/friends/Friends.js
> +    setCurrentResults(results)
When the search form is cleared, the existing friends are not rendered. The UI is stuck in a state with no friends displayed. It is because you are not re-rendering the component when the search form is cleared.

2022-05-09 13:52 UTC, moody2times commented on client/src/components/friends/Friends.js
> +        .splice(friends.indexOf(friendId), 1),
I just want to make this as a note, but this is a pretty expensive operation with O(n3). `map` is one loop, `splice` is another expensive operation, then `indexOf` is third loop. Isn't there a better way?
However, this is just a note because we don't have time for optimization now.

2022-05-09 13:52 UTC, moody2times commented on client/src/components/friends/Friends.js
> +  const container = 'Friends'
The name of this const is confusing when I finish tracing to see what it does. This is just a note

2022-05-09 13:52 UTC, moody2times commented on client/src/components/friends/Friends.js
> +      !friends.some((f) => f.id === friend.id)
Is there a simpler way to get the id of the friend deleted without these double loops? Just a note.

2022-05-09 14:24 UTC, KhadidjaArezki commented on client/src/components/friends/Friends.js
> +      !friends.some((f) => f.id === friend.id)
Not that I am aware of, but I am open to suggestions.

2022-05-09 14:44 UTC, KhadidjaArezki commented on client/src/components/friends/Friends.js
> +        .splice(friends.indexOf(friendId), 1),
Noted. Wait... Has it not been said that "Premature optimization is the root of all evil"?

2022-05-09 14:47 UTC, KhadidjaArezki commented on client/src/components/friends/Friends.js
> +  const container = 'Friends'
Can you propose a name? I could not think of a better name.

2022-05-09 15:10 UTC, KhadidjaArezki commented on client/src/components/friends/Friends.js
> +    setCurrentResults(results)
The current implementation of the search box does not manage the state of the input field. I think it's called an uncontrolled component. It does not respond to changes in the input field, but only to the submit button/enter key.

2022-05-09 15:30 UTC, moody2times commented on client/src/components/friends/Friends.js
> +    setCurrentResults(results)
Okay, then. As I said, the only changes I want you to make for now is adding comments for readability.

2022-05-09 15:31 UTC, uwojeyamudiaga commented on client/src/components/friends/Friends.js
> +        .splice(friends.indexOf(friendId), 1),
😆 we will see about it later when we have the time. I am requesting this a change right now.

2022-05-09 15:33 UTC, uwojeyamudiaga commented on client/src/components/friends/Friends.js
> +  const container = 'Friends'
Since you used it as placeholder (if I remember correctly), maybe placeholderText or something similar.

2022-05-09 15:34 UTC, moody2times commented on client/src/components/friends/Friends.js
> +      !friends.some((f) => f.id === friend.id)
Well, when the friend is deleted, the delete action is triggered by a user event. We can get the `id` from that event. However, this is just a note for now.

2022-05-09 19:04 UTC, uwojeyamudiaga approved these changes
Thanks for your hard work.

2022-05-09 19:07 UTC, merged